BI-9948 Correct retry and error topic naming in configuration
companieshouse/item-handler pull request #70
Opened 2022-01-14 08:07 UTC by phudson-ch

* Correct retry and error topic naming in configuration
* Improve logging output by adding attempt to response handler log output

Relates to: [BI-9948 Fix issues with Kafka resilience in Item Handler](https://companieshouse.atlassian.net/browse/BI-9947)

2022-01-14 09:20 UTC, dlgroves-ch requested changes
Please rename `kafka.topics.order-received-notification-*` properties and all usages to `kafka.topics.order-received-*`.

2022-01-14 09:20 UTC, dlgroves-ch commented on src/main/resources/application.properties
> +kafka.topics.order-received-notification-retry=order-received-retry
Please rename this property `kafka.topics.order-received-retry`

2022-01-14 09:20 UTC, dlgroves-ch commented on src/main/resources/application.properties
> +kafka.topics.order-received-notification-error=order-received-error
Please rename this property `kafka.topics.order-received-error`

2022-01-14 09:20 UTC, dlgroves-ch commented on src/test/resources/application.properties
> +kafka.topics.order-received-notification-retry=order-received-retry
Please rename this property `kafka.topics.order-received-retry`

2022-01-14 09:20 UTC, dlgroves-ch commented on src/test/resources/application.properties
> +kafka.topics.order-received-notification-error=order-received-error
`Please rename this property kafka.topics.order-received-error`

2022-01-14 11:08 UTC, cgregoryCH commented on src/main/resources/application.properties
> +response.handler.maximumRetryAttempts = 1
Should this value be 1 or 5?

2022-01-17 09:53 UTC, phudson-ch commented on src/main/resources/application.properties
> +response.handler.maximumRetryAttempts = 1
Should be 5 - fixed

2022-02-28 13:53 UTC, phudson-ch commented
No longer required - change made as part of another PR

2022-02-28 13:53 UTC, closed without merging